### ISSUE TITLE
new folder

### ISSUE THREAD

**Issue by miletto** [ubimus/ubimus.github.io#1]
Oi Victor. 
Se topares, umas pequenas alterações para personalizar o repositório.
Preciso criar uma pasta img e inserir 2 arquivos (o de fundo e o um logo do ubimus). 
Se achas que não é caso, sem grilo algum.
Abraço.

**Comment by vlazzarini** [comment]
Oi Evandro, já o convidei ao projeto. Vc deve ter full access.

**Comment by miletto** [comment]
Valeu, obrigado.
Grande abraço.

## 

Evandro Manara Miletto
http://evandromanara.net/
IFRS Campus Porto Alegre
Rua Cel Vicente, 281 - Centro
Porto Alegre, RS - 90030-041
- 55 51 3930.6040

2015-07-08 9:37 GMT-03:00 vlazzarini notifications@github.com:
